# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
    - restapi*
  paths:
    include:
    - sdk/core/
    - eng/
    - tools/
    exclude:
    - eng/common/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
    - restapi*
  paths:
    include:
    - sdk/core/
    - eng/
    - tools/
    exclude:
    - eng/common/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: core
    BuildTargetingString: generic-core
    ValidateFormatting: true
    Artifacts:
    - name: generic-core
      safeName: generic-core
